# Generated by Django 4.1 on 2022-08-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_item_desc_item_img_alter_item_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='other')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.TextField(default='other'),
        ),
    ]
