# Generated by Django 4.1 on 2022-08-21 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_products_cart_price_cart_category_cart_desc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='price',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='img',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='name',
        ),
    ]
