# Generated by Django 4.1 on 2022-08-26 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_cart_quantity_item_discount_item_discount_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 26, 11, 50, 10, 443735)),
        ),
        migrations.AddField(
            model_name='order',
            name='pro',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.TextField(default='ordered'),
        ),
        migrations.AddField(
            model_name='order',
            name='sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='zip',
            field=models.TextField(default=''),
        ),
    ]
