# Generated by Django 4.1 on 2022-08-26 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_order_product_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estimated_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 26, 11, 52, 31, 494819)),
        ),
        migrations.AlterField(
            model_name='order',
            name='sum',
            field=models.IntegerField(default=0),
        ),
    ]
