# Generated by Django 4.1 on 2022-08-26 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_order_estimated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estimated_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 26, 11, 54, 44, 761466)),
        ),
    ]
