# Generated by Django 4.1 on 2022-08-26 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_order_estimated_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='sum',
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 26, 11, 55, 19, 479153)),
        ),
    ]
