# Generated by Django 4.1 on 2022-08-26 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_order_sum_alter_order_estimated_date'),
    ]

    operations = [
        
    ]
