# Generated by Django 4.1 on 2022-08-26 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_order_address_remove_order_city_and_more'),
    ]

    operations = [
        
    ]
