# Generated by Django 4.1 on 2022-08-26 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='estimated_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 26, 12, 16, 33, 985158)),
        ),
    ]
