# Generated by Django 4.1 on 2022-08-26 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_orders_estimated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='estimated_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
